"""
setup_models.py — Download Phi-3-mini-4k-instruct and Qwen2.5-Coder-3B GGUF models.

Run this ONCE before starting NeuroClaw Bot:
    python setup_models.py

This script downloads both models into the models/ directory.
Total disk space needed: ~4.2 GB (Phi-3 ~2.2GB + Qwen-Coder-3B ~2.0GB)
"""
import os
import sys
import subprocess
from pathlib import Path

AGENT_DIR = Path(__file__).parent.resolve()
MODELS_DIR = AGENT_DIR / "models"


# ── Model definitions ──────────────────────────────────────────────────────────
MODELS = [
    {
        "name": "Qwen2.5-Coder-3B-Instruct",
        "role": "coder",
        "repo": "Qwen/Qwen2.5-Coder-3B-Instruct-GGUF",
        "filename": "qwen2.5-coder-3b-instruct-q4_k_m.gguf",
        "description": "Best for code writing, editing, debugging (~2.0 GB)",
        "size_gb": 2.0,
    },
    {
        "name": "Phi-3-mini-4k-instruct",
        "role": "planner",
        "repo": "microsoft/Phi-3-mini-4k-instruct-gguf",
        "filename": "Phi-3-mini-4k-instruct-q4.gguf",
        "description": "Best for reasoning, planning, explaining (~2.2 GB)",
        "size_gb": 2.2,
    },
]


def check_huggingface_hub() -> bool:
    """Check if huggingface-hub is installed."""
    try:
        import huggingface_hub  # type: ignore[import]  # noqa: F401
        return True
    except ImportError:
        return False


def download_model(model: dict) -> bool:
    """Download a single model using huggingface-hub."""
    from huggingface_hub import hf_hub_download  # type: ignore

    dest = MODELS_DIR / model["filename"]
    if dest.exists():
        size_mb = dest.stat().st_size / (1024 * 1024)
        print(f"  ✅ Already exists: {model['filename']} ({size_mb:.0f} MB)")
        return True

    print(f"  ⬇  Downloading {model['name']}...")
    print(f"     Repo   : {model['repo']}")
    print(f"     File   : {model['filename']}")
    print(f"     Size   : ~{model['size_gb']} GB  (this will take a while on slow connections)")
    print()

    try:
        hf_hub_download(
            repo_id=model["repo"],
            filename=model["filename"],
            local_dir=str(MODELS_DIR),
            local_dir_use_symlinks=False,
        )
        print(f"  ✅ Downloaded: {model['filename']}")
        return True
    except Exception as e:
        print(f"  ❌ Failed to download {model['filename']}: {e}")
        return False


def write_model_config():
    """Write/update config.yaml to reference both downloaded models."""
    config_path = AGENT_DIR / "config.yaml"
    config_content = (
        "# NeuroClaw Bot — Dual Model Configuration\n"
        "# Auto-generated by setup_models.py\n"
        "\n"
        "# Phi-3-mini: Planner / Reasoning model\n"
        "planner_model: models/Phi-3-mini-4k-instruct-q4.gguf\n"
        "planner_ctx: 8192\n"
        "\n"
        "# Qwen2.5-Coder-3B: Code generation model\n"
        "coder_model: models/qwen2.5-coder-3b-instruct-q4_k_m.gguf\n"
        "coder_ctx: 8192\n"
        "\n"
        "# GPU Offload: 0=CPU only, 20-35=partial GPU, -1=full GPU\n"
        "n_gpu_layers: 0\n"
        "\n"
        "# Agent Behavior\n"
        "max_iterations: 12\n"
        "\n"
        "# RAG Settings\n"
        "top_k_retrieval: 3\n"
        "embedding_model: all-MiniLM-L6-v2\n"
        "\n"
        "# Telegram Remote Control (optional)\n"
        "# telegram_token: YOUR_BOT_TOKEN\n"
        "# telegram_allowed_user_ids:\n"
        "#   - 123456789\n"
    )
    config_path.write_text(config_content, encoding="utf-8")
    print(f"\n  ✅ config.yaml updated with dual-model paths.")


def main():
    print("\n" + "=" * 60)
    print("  🧠 NeuroClaw Bot — Model Download Setup")
    print("=" * 60)
    print(f"\n  Models directory: {MODELS_DIR}")
    print(f"  Estimated total size: ~4.2 GB\n")

    # Check / install huggingface_hub
    if not check_huggingface_hub():
        print("  Installing huggingface-hub...")
        # Use subprocess.run with a list — safe even when Python path has spaces
        subprocess.run(
            [sys.executable, "-m", "pip", "install", "huggingface-hub", "-q"],
            check=False,
        )
        if not check_huggingface_hub():
            print("  ❌ Could not install huggingface-hub. Run manually:")
            print("     pip install huggingface-hub")
            sys.exit(1)

    MODELS_DIR.mkdir(exist_ok=True)

    # Download each model
    success = []
    for model in MODELS:
        print(f"\n── {model['role'].upper()} MODEL: {model['name']} ──")
        print(f"   {model['description']}")
        ok = download_model(model)
        success.append(ok)

    # Summary
    print("\n" + "=" * 60)
    print("  DOWNLOAD SUMMARY")
    print("=" * 60)
    for model, ok in zip(MODELS, success):
        status = "✅" if ok else "❌"
        print(f"  {status}  {model['name']} ({model['role']})")

    if all(success):
        write_model_config()
        print("\n  ✅ Both models ready! Start the agent with:")
        print("     cd your-project")
        print(f"     python {AGENT_DIR / 'agent.py'}\n")
    else:
        print("\n  ⚠  Some models failed. You can re-run this script to retry.")
        print("  Or manually copy .gguf files to:", MODELS_DIR)


if __name__ == "__main__":
    main()
